/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datamanagerbuku.ui;

import datamanagerbuku.database.BukuDataSource;
import datamanagerbuku.models.Buku;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rudigigihprabowo
 */
public class FormBukuActivity extends javax.swing.JFrame {

    /**
     * Creates new form FormBukuActivity
     */
    public FormBukuActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleActivity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        judulField = new javax.swing.JTextField();
        pengarangField = new javax.swing.JTextField();
        yudhistiraRb = new javax.swing.JRadioButton();
        airlanggaRb = new javax.swing.JRadioButton();
        gramediaRb = new javax.swing.JRadioButton();
        ygLainRb = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tahunTerbitCb = new javax.swing.JComboBox();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleActivity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titleActivity.setText("Form Buku");

        jLabel2.setText("Judul");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Penerbit");

        pengarangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengarangFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(yudhistiraRb);
        yudhistiraRb.setText("Yudhistira");

        buttonGroup1.add(airlanggaRb);
        airlanggaRb.setSelected(true);
        airlanggaRb.setText("Airlangga");
        airlanggaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlanggaRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(gramediaRb);
        gramediaRb.setText("Gramedia");

        buttonGroup1.add(ygLainRb);
        ygLainRb.setText("Yang Lain");

        jLabel5.setText("Tahun Terbit");

        tahunTerbitCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleActivity)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(judulField)
                                .addComponent(pengarangField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addComponent(tahunTerbitCb, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yudhistiraRb)
                                    .addComponent(airlanggaRb))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ygLainRb)
                                    .addComponent(gramediaRb))))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(judulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yudhistiraRb)
                    .addComponent(gramediaRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlanggaRb)
                    .addComponent(ygLainRb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tahunTerbitCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pengarangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengarangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengarangFieldActionPerformed

    private void airlanggaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlanggaRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlanggaRbActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBukuActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBukuActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton airlanggaRb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton gramediaRb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField judulField;
    private javax.swing.JTextField pengarangField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox tahunTerbitCb;
    private javax.swing.JLabel titleActivity;
    private javax.swing.JRadioButton ygLainRb;
    private javax.swing.JRadioButton yudhistiraRb;
    // End of variables declaration//GEN-END:variables

    private Buku buku;

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showSucceed(String message) {
        JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showOldDataOf(Buku buku) {
        judulField.setText(buku.getJudulBuku());
        pengarangField.setText(buku.getPengarang());

        String penerbit = buku.getPenerbit();
        switch (penerbit) {
            case "Yudhistira":
                yudhistiraRb.setSelected(true);
                break;
            case "Gramedia":
                gramediaRb.setSelected(true);
                break;
            case "Airlangga":
                airlanggaRb.setSelected(true);
                break;
            default:
                ygLainRb.setSelected(true);
                break;
        }

        tahunTerbitCb.setSelectedItem(String.valueOf(buku.getTahunTerbit()));
    }

    public void setBuku(Buku buku) {
        this.buku = buku;
        showOldDataOf(buku);
    }

    private String getSelectedPenerbit() {
        if (yudhistiraRb.isSelected()) {
            return "Yudhistira";
        } else if (gramediaRb.isSelected()) {
            return "Gramedia";
        } else if (airlanggaRb.isSelected()) {
            return "Airlangga";
        } else if (ygLainRb.isSelected()) {
            return "Yang Lain";
        } else {
            return "";
        }
    }

    private boolean validateAllInput() {
        String judul = judulField.getText();
        if (judul.isEmpty()) {
            showError("Judul buku masih kosong");
            return false;
        }
        String pengarang = pengarangField.getText();
        if (pengarang.isEmpty()) {
            showError("Pengarang buku masih kosong");
            return false;
        }
        String penerbit = getSelectedPenerbit();
        if (penerbit.isEmpty()) {
            showError("Penerbit belum ada yang dipilih");
            return false;
        }
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();
        if (tahunTerbit.isEmpty()) {
            showError("Tahun terbit belum ada yang dipilih");
            return false;
        }

        return true;
    }

    private void collectDataFor(Buku buku) {
        String judul = judulField.getText();
        String pengarang = pengarangField.getText();
        String penerbit = getSelectedPenerbit();
        String tahunTerbit = tahunTerbitCb.getSelectedItem().toString();

        buku.setJudulBuku(judul);
        buku.setPengarang(pengarang);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(Integer.parseInt(tahunTerbit));
    }

    private void saveNewData() {
        buku = new Buku();
        collectDataFor(buku);

        BukuDataSource datasource = new BukuDataSource();
        try {
            datasource.save(buku);
            showSucceed("Data buku berhasil disimpan");
        } catch (SQLException e) {
            showError("Data buku gagal disimpan");
            e.printStackTrace();
        }
    }

    private void updateData() {
        collectDataFor(buku);

        BukuDataSource datasource = new BukuDataSource();
        try {
            datasource.update(buku);
            showSucceed("Data buku berhasil diperbaharui");
        } catch (SQLException e) {
            showError("Data buku gagal diperbaharui");
            e.printStackTrace();
        }
    }

    private void simpan() {
        if (!validateAllInput()) {
            return;
        }

        if (buku != null) {
            updateData();
        } else {
            saveNewData();
        }
    }

    @Override
    public void setTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
        titleActivity.setText(title);
    }
}
